{% set name = "isingchat" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name | lower }}"
  version: {{ version }}

source:
  git_url: git+ssh://git@github.com/oarodriguez/isingchat.git
  git_rev: {{ version }}
#  sha256: 5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7

build:
  number: 1
  noarch: python
  script:
    - poetry build -f sdist -vv
    - "{{ PYTHON }} -m tarfile -e ./dist/{{ name | lower }}-{{ version }}.tar.gz ./dist/"
    - "rm -f ./dist/{{ name | lower }}-{{ version }}/pyproject.toml"  # [not win]
    - "del /f .\\dist\\{{ name | lower }}-{{ version }}\\pyproject.toml"  # [win]
    - "{{ PYTHON }} -m pip install ./dist/{{ name | lower }}-{{ version }} --no-deps --ignore-installed -vv"

  entry_points:
    - isingchat = isingchat.cli:main

requirements:
  host:
    - python
    - poetry>=1.0
  run:
    - python>=3.7
    - attrs
    - importlib-metadata>=3.3.0
    - numpy>=1.19.0
    - scipy>=1.4
    - matplotlib
    - numba>=0.50.0
    - click
    - rich
    - "ruamel.yaml"
    - dask
    - h5py
    - pandas

test:
  imports:
    - isingchat
  commands:
    - isingchat --help

about:
  home: https://github.com/oarodriguez/isingchat
  summary: A library to calculate the thermodynamic properties of a 1D Ising spin chain with beyond nearest-neighbor interactions.
